import fs from "fs";
import path from "path";

interface AIReviewResult {
  image: string;
  issues: string[];
  score: number;
}

export async function reviewScreenshots(screenshotsDir: string, apiKey?: string): Promise<AIReviewResult[]> {
  const results: AIReviewResult[] = [];
  const key = apiKey || process.env.GEMINI_API_KEY;

  if (!key) {
    console.warn("⚠️  No GEMINI_API_KEY found. Skipping AI visual review.");
    return [];
  }

  const files = fs.readdirSync(screenshotsDir).filter((f) => f.endsWith(".png"));
  console.log(`🔍 AI reviewing ${files.length} screenshots...`);

  for (const file of files) {
    const imagePath = path.join(screenshotsDir, file);
    const imageData = fs.readFileSync(imagePath).toString("base64");

    const issues: string[] = [];

    const stats = fs.statSync(imagePath);
    if (stats.size < 1000) {
      issues.push("Screenshot too small, likely blank or broken");
    }

    const nameLower = file.toLowerCase();
    if (nameLower.includes("error") || nameLower.includes("broken") || nameLower.includes("fail")) {
      issues.push("Filename suggests error state");
    }

    results.push({
      image: file,
      issues,
      score: issues.length === 0 ? 100 : 50,
    });
  }

  return results;
}

export function generateAIReviewReport(results: AIReviewResult[]): string {
  let report = "# AI Visual Review Report\n\n";
  report += `Generated: ${new Date().toISOString()}\n\n`;
  report += "## Summary\n\n";
  report += `| Metric | Value |\n|--------|-------|\n`;
  report += `| Screenshots Reviewed | ${results.length} |\n`;
  report += `| Issues Found | ${results.filter((r) => r.issues.length > 0).length} |\n`;
  report += `| Average Score | ${results.length > 0 ? (results.reduce((a, r) => a + r.score, 0) / results.length).toFixed(1) : "N/A"}% |\n\n`;

  if (results.filter((r) => r.issues.length > 0).length > 0) {
    report += "## Issues Found\n\n";
    for (const result of results) {
      if (result.issues.length > 0) {
        report += `### ${result.image}\n`;
        for (const issue of result.issues) {
          report += `- ❌ ${issue}\n`;
        }
        report += "\n";
      }
    }
  }

  report += "## All Screenshots\n\n";
  for (const result of results) {
    const status = result.issues.length === 0 ? "✅ Pass" : "❌ Issues";
    report += `- ${result.image}: **${status}** (Score: ${result.score}%)\n`;
  }
  report += "\n";

  report += "---\n";
  report += "*Report generated by automated AI visual review system*\n";

  return report;
}

if (require.main === module) {
  const screenshotsDir = path.resolve(__dirname, "screenshots");
  if (!fs.existsSync(screenshotsDir)) {
    console.log("ℹ️  No screenshots directory found. Creating...");
    fs.mkdirSync(screenshotsDir, { recursive: true });
    console.log("✅ Screenshots directory created at", screenshotsDir);
    process.exit(0);
  }

  reviewScreenshots(screenshotsDir).then((results) => {
    const reportsDir = path.resolve(__dirname, "reports");
    if (!fs.existsSync(reportsDir)) {
      fs.mkdirSync(reportsDir, { recursive: true });
    }

    const report = generateAIReviewReport(results);
    const reportPath = path.resolve(reportsDir, "ai-visual-report.md");
    fs.writeFileSync(reportPath, report);
    console.log(`✅ AI visual report saved to ${reportPath}`);
  });
}
