import fs from "fs";
import path from "path";

interface TestResult {
  file: string;
  passed: number;
  failed: number;
  skipped: number;
  duration: number;
}

interface QAReport {
  timestamp: string;
  totalTests: number;
  passed: number;
  failed: number;
  skipped: number;
  brokenPages: string[];
  consoleErrors: string[];
  networkErrors: string[];
  firestoreBudgetFailures: string[];
  feeModuleResult: string;
  duplicatePaymentResult: string;
  mobileIssues: string[];
  receiptIssues: string[];
  lighthouseSummary: string;
  aiReviewSummary: string;
}

export function generateQAReport(data: Partial<QAReport>): string {
  const report: QAReport = {
    timestamp: new Date().toISOString(),
    totalTests: 0,
    passed: 0,
    failed: 0,
    skipped: 0,
    brokenPages: [],
    consoleErrors: [],
    networkErrors: [],
    firestoreBudgetFailures: [],
    feeModuleResult: "⚠️  Not run",
    duplicatePaymentResult: "⚠️  Not run",
    mobileIssues: [],
    receiptIssues: [],
    lighthouseSummary: "⚠️  Not run",
    aiReviewSummary: "⚠️  Not run",
    ...data,
  };

  let md = "# Sri Narayana ERP - Final QA Report\n\n";
  md += `**Generated:** ${report.timestamp}\n\n`;
  md += "---\n\n";

  md += "## 📊 Test Summary\n\n";
  md += `| Metric | Value |\n|--------|-------|\n`;
  md += `| Total Tests | ${report.totalTests} |\n`;
  md += `| ✅ Passed | ${report.passed} |\n`;
  md += `| ❌ Failed | ${report.failed} |\n`;
  md += `| ⏭️  Skipped | ${report.skipped} |\n`;
  md += `| Pass Rate | ${report.totalTests > 0 ? ((report.passed / report.totalTests) * 100).toFixed(1) : "N/A"}% |\n\n`;

  if (report.brokenPages.length > 0) {
    md += "## 🚫 Broken Pages\n\n";
    for (const page of report.brokenPages) md += `- ${page}\n`;
    md += "\n";
  }

  if (report.consoleErrors.length > 0) {
    md += "## ⚠️ Console Errors\n\n";
    for (const err of report.consoleErrors) md += `- \`${err}\`\n`;
    md += "\n";
  }

  if (report.networkErrors.length > 0) {
    md += "## 🌐 Network Errors\n\n";
    for (const err of report.networkErrors) md += `- ${err}\n`;
    md += "\n";
  }

  if (report.firestoreBudgetFailures.length > 0) {
    md += "## 🔥 Firestore Budget Failures\n\n";
    md += "| Page | Budget | Actual |\n|------|--------|--------|\n";
    for (const f of report.firestoreBudgetFailures) {
      const parts = f.split("|").map((s) => s.trim());
      if (parts.length >= 3) {
        md += `| ${parts[0]} | ${parts[1]} | ${parts[2]} |\n`;
      } else {
        md += `| ${f} | N/A | N/A |\n`;
      }
    }
    md += "\n";
  }

  md += "## 💰 Fee Module\n\n";
  md += `${report.feeModuleResult}\n\n`;

  md += "## 🔄 Duplicate Payment Prevention\n\n";
  md += `${report.duplicatePaymentResult}\n\n`;

  if (report.mobileIssues.length > 0) {
    md += "## 📱 Mobile/Tablet UI Issues\n\n";
    for (const issue of report.mobileIssues) md += `- ${issue}\n`;
    md += "\n";
  }

  if (report.receiptIssues.length > 0) {
    md += "## 🧾 Receipt/Print Issues\n\n";
    for (const issue of report.receiptIssues) md += `- ${issue}\n`;
    md += "\n";
  }

  md += "## 📁 Reports & Artifacts\n\n";
  md += `| Report | Location |\n|--------|----------|\n`;
  md += `| Playwright HTML Report | \`tests/reports/playwright-report/index.html\` |\n`;
  md += `| Screenshots | \`tests/screenshots/\` |\n`;
  md += `| Lighthouse Report | \`tests/reports/lighthouse/\` |\n`;
  md += `| AI Visual Review | \`tests/reports/ai-visual-report.md\` |\n\n`;

  md += "## 🏠 Lighthouse Summary\n\n";
  md += `${report.lighthouseSummary}\n\n`;

  md += "## 🤖 AI Visual Review Summary\n\n";
  md += `${report.aiReviewSummary}\n\n`;

  md += "## 🔧 Recommended Fixes\n\n";
  md += "Based on the test results, the following areas may need attention:\n\n";
  md += "1. **Broken Pages** — Check routes listed above for 404/500 errors or permission denied\n";
  md += "2. **Console Errors** — Review uncaught exceptions and fix JavaScript errors\n";
  md += "3. **Firestore Budget** — Optimize queries for pages exceeding read budgets\n";
  md += "4. **Mobile Layout** — Fix horizontal scroll, overlapping elements on small viewports\n";
  md += "5. **Accessibility** — Ensure all form inputs have proper labels and ARIA attributes\n";
  md += "6. **Receipt Module** — Verify PDF generation and print layout\n";
  md += "7. **Dark Mode** — Check text contrast in dark theme across all pages\n\n";

  md += "---\n";
  md += `*Report generated by automated QA system at ${report.timestamp}*\n`;

  return md;
}

export function parsePlaywrightReport(reportPath: string): Partial<QAReport> {
  try {
    const reportData = JSON.parse(fs.readFileSync(reportPath, "utf-8"));
    const suites = reportData.suites || [];
    let totalTests = 0;
    let passed = 0;
    let failed = 0;
    let skipped = 0;

    function walkSuite(suite: any) {
      for (const spec of suite.specs || []) {
        totalTests++;
        const ok = spec.ok || spec.tests?.every((t: any) => t.status === "expected" || t.status === "passed");
        if (ok) passed++;
        else if (spec.tests?.some((t: any) => t.status === "skipped")) skipped++;
        else failed++;
      }
      for (const child of suite.suites || []) walkSuite(child);
    }

    for (const suite of suites) walkSuite(suite);

    return { totalTests, passed, failed, skipped };
  } catch {
    console.warn("⚠️  Could not parse Playwright report at", reportPath);
    return {};
  }
}

if (require.main === module) {
  const reportsDir = path.resolve(__dirname, "reports");
  if (!fs.existsSync(reportsDir)) {
    fs.mkdirSync(reportsDir, { recursive: true });
  }

  const reportPath = path.resolve(reportsDir, "final-qa-report.md");

  const parsed = parsePlaywrightReport(
    path.resolve(reportsDir, "playwright-report", "report.json")
  );

  const report = generateQAReport({
    ...parsed,
  });

  fs.writeFileSync(reportPath, report);
  console.log(`✅ QA report saved to ${reportPath}`);
}
