import { NextResponse } from "next/server";
import { adminDb, verifyBearerToken } from "@/lib/firebaseAdmin";

const ERASABLE_COLLECTIONS = [
  "users",
  "teachers",
  "attendance",
  "attendance_logs",
  "biometric_logs",
  "holidays",
  "salary_reports",
  "settings",
  "password_reset_requests",
  "password_reset_history",
  "leave_requests",
  "attendance_edit_audit_logs",
  "admin_notifications"
];

const CONFIRMATION_PHRASE = "ERASE SCHOOL DATA";

async function deleteCollection(collectionName: string) {
  const db = adminDb();
  let deleted = 0;

  while (true) {
    const snapshot = await db.collection(collectionName).limit(400).get();
    if (snapshot.empty) break;

    const batch = db.batch();
    snapshot.docs.forEach((doc) => batch.delete(doc.ref));
    await batch.commit();
    deleted += snapshot.size;
  }

  return deleted;
}

export async function POST(req: Request) {
  try {
    const decodedToken = await verifyBearerToken(req);
    if (!decodedToken || (decodedToken.role !== "admin" && decodedToken.role !== "super_admin")) {
      return NextResponse.json({ ok: false, error: "Admin access required" }, { status: 403 });
    }

    const body = await req.json();
    const backupChecksum = String(body.backupChecksum ?? "").trim();
    const confirmationPhrase = String(body.confirmationPhrase ?? "").trim();
    const savedToUsb = Boolean(body.savedToUsb);

    if (!savedToUsb) {
      return NextResponse.json({ ok: false, error: "USB backup confirmation is required" }, { status: 400 });
    }
    if (confirmationPhrase !== CONFIRMATION_PHRASE) {
      return NextResponse.json({ ok: false, error: "Confirmation phrase does not match" }, { status: 400 });
    }
    if (!backupChecksum) {
      return NextResponse.json({ ok: false, error: "Backup checksum is required" }, { status: 400 });
    }

    const db = adminDb();
    const backupDoc = await db.collection("backup_audit_logs").doc(backupChecksum).get();
    if (!backupDoc.exists) {
      return NextResponse.json({ ok: false, error: "Backup checksum was not generated by this system" }, { status: 400 });
    }

    const deletedCounts: Record<string, number> = {};
    for (const collectionName of ERASABLE_COLLECTIONS) {
      deletedCounts[collectionName] = await deleteCollection(collectionName);
    }

    await db.collection("backup_audit_logs").doc(backupChecksum).set(
      {
        usedForErase: true,
        erasedAt: new Date().toISOString(),
        erasedBy: decodedToken.uid,
        deletedCounts
      },
      { merge: true }
    );
    await db.collection("admin_audit_logs").add({
      action: "erase_data_after_usb_backup",
      backupChecksum,
      deletedCounts,
      createdAt: new Date().toISOString(),
      createdBy: decodedToken.uid
    });

    return NextResponse.json({ ok: true, deletedCounts });
  } catch (error) {
    const message = error instanceof Error ? error.message : "Unable to erase data";
    return NextResponse.json({ ok: false, error: message }, { status: 400 });
  }
}
