import { adminDb } from "@/lib/firebaseAdmin";
import { requireSuperAdmin, json } from "@/lib/apiUtils";

// Collections that MUST survive an erase. They record that the erase happened
// and preserve the tamper-evident audit trail used to authorize it — deleting
// them would destroy the evidence of the very operation being performed.
//
// Everything else is discovered at runtime via listCollections() rather than a
// hardcoded allow-list, which previously drifted out of date: finance, exams,
// fees, transport, library, hostel, inventory and other modules were silently
// left behind by an erase, giving a false sense of a clean wipe.
const PRESERVED_COLLECTIONS = new Set([
  "backup_audit_logs",
  "admin_audit_logs",
  "audit_logs"
]);

const CONFIRMATION_PHRASE = "ERASE SCHOOL DATA";

async function deleteCollection(collectionName: string) {
  const db = adminDb();
  let deleted = 0;

  while (true) {
    const snapshot = await db.collection(collectionName).limit(400).get();
    if (snapshot.empty) break;

    const batch = db.batch();
    snapshot.docs.forEach((doc) => batch.delete(doc.ref));
    await batch.commit();
    deleted += snapshot.size;
  }

  return deleted;
}

export async function POST(req: Request) {
  try {
    const decodedToken = await requireSuperAdmin(req);
    if (!decodedToken) {
      return json({ ok: false, error: "Super admin access required" }, { status: 403 });
    }

    const body = await req.json();
    const backupChecksum = String(body.backupChecksum ?? "").trim();
    const confirmationPhrase = String(body.confirmationPhrase ?? "").trim();
    const savedToUsb = Boolean(body.savedToUsb);

    if (!savedToUsb) {
      return json({ ok: false, error: "USB backup confirmation is required" }, { status: 400 });
    }
    if (confirmationPhrase !== CONFIRMATION_PHRASE) {
      return json({ ok: false, error: "Confirmation phrase does not match" }, { status: 400 });
    }
    if (!backupChecksum) {
      return json({ ok: false, error: "Backup checksum is required" }, { status: 400 });
    }

    const db = adminDb();
    const backupDoc = await db.collection("backup_audit_logs").doc(backupChecksum).get();
    if (!backupDoc.exists) {
      return json({ ok: false, error: "Backup checksum was not generated by this system" }, { status: 400 });
    }

    // Discover every top-level collection at runtime so newly added modules are
    // wiped automatically. Preserved audit/backup collections are skipped.
    const allCollections = await db.listCollections();
    const deletedCounts: Record<string, number> = {};
    for (const collection of allCollections) {
      if (PRESERVED_COLLECTIONS.has(collection.id)) continue;
      deletedCounts[collection.id] = await deleteCollection(collection.id);
    }

    await db.collection("backup_audit_logs").doc(backupChecksum).set(
      {
        usedForErase: true,
        erasedAt: new Date().toISOString(),
        erasedBy: decodedToken.uid,
        deletedCounts
      },
      { merge: true }
    );
    await db.collection("admin_audit_logs").add({
      action: "erase_data_after_usb_backup",
      backupChecksum,
      deletedCounts,
      createdAt: new Date().toISOString(),
      createdBy: decodedToken.uid
    });

    return json({ ok: true, deletedCounts });
  } catch (error) {
    const message = error instanceof Error ? error.message : "Unable to erase data";
    return json({ ok: false, error: message }, { status: 400 });
  }
}

