export const TEST_CONFIG = {
  baseUrl: process.env.BASE_URL || "http://localhost:3000",
  useEmulator: process.env.NEXT_PUBLIC_USE_FIREBASE_EMULATOR === "true",
  emulatorHost: "localhost",
  emulatorAuthPort: 9099,
  emulatorFirestorePort: 8080,
  defaultPassword: "Test@123",
  timeouts: {
    navigation: 15000,
    networkIdle: 10000,
    element: 5000,
    animation: 1000,
  },
  viewports: {
    mobile: { width: 390, height: 844 },
    tablet: { width: 768, height: 1024 },
    laptop: { width: 1366, height: 768 },
    desktop: { width: 1920, height: 1080 },
  },
  budgets: {
    studentProfileReads: 50,
    studentListReads: 100,
    feeDashboardReads: 150,
    dueListReads: 100,
    attendancePageReads: 150,
    settingsPageReads: 50,
    studentEditWrites: 5,
    paymentSaveWrites: 10,
  },
};
